[package]
name = "hex-patch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
cpp_demangle = "0.4.3"
crossterm = "0.27.0"
iced-x86 = "1.21.0"
object = "0.34.0"
pdb = "0.8.0"
ratatui = "0.26.1"
tempfile = "3.10.1"
which = "6.0.0"
